export const Data=[
    {
        id:1,
        image:"../../assets/image_1.jpg"
    },
    {
        id:2,
        image:"../../assets/image_1.jpg"
    },
    {
        id:3,
        image:"../../assets/image_1.jpg"
    },
    {
        id:4,
        image:"../../assets/image_1.jpg"
    },
    {
        id:5,
        image:"../../assets/image_1.jpg"
    },
    {
        id:6,
        image:"../../assets/image_1.jpg"
    },
    {
        id:7,
        image:"../../assets/image_1.jpg"
    },
    {
        id:8,
        image:"../../assets/image_1.jpg"
    },
    {
        id:9,
        image:"../../assets/image_1.jpg"
    },
    {
        id:10,
        image:"../../assets/image_1.jpg"
    },
]